#! /bin/bash
echo "REMEMBER TO CHECKIN"
checkIn()
{
	#in shell script we don't need to declare variable individually 
	for file in $( ls *.h) $( ls *.cpp)
	do
		ci $file
	done

}
checkOut()
{	for file in $( ls *.h,v) $( ls *.cpp,v)
	do
		co $file
	done	
}
cofordev()
{
	for file in $( ls *.h,v ) $( ls *.cpp,v )
	do
		co -l $file
	done
}
runProgram()
{	
	echo
	read -n1 -p " Do you want to run the program(Y/N) : "
	echo
	if [ $REPLY = 'y' ]
	then 
		./lms
	
	elif [ $REPLY = 'n' ]
	
	then
		exit
		
	fi

}
buildProgram()
{
	checkOut
	if ( make )
	then
		echo "Program Build Successfully"
		runProgram
		echo
	else
		echo "PROGRAM BUILD FAILED!"
		echo
	fi
}
buildProgram
while ( true )
do
	echo
	echo "1-->For file checkIn"
	echo "2-->For file checkOut"
	echo "3-->For file checkOut for development"
	echo "4-->For program buildup"
	echo "5-->For running the program"
	echo "0-->For EXIT"
	echo
	read -n1 -p "Enter the choice : " 
		
	case $REPLY in 
		1)
		       	checkIn
			;;	
		2)
			checkOut
			;;
		3)
			cofordev
			;;
		5)
			runProgram
			;;
		4)
			buildProgram
			;;
		0)
			echo
			echo "REMEMBER TO CHECK OUT"
			echo
			exit 0
	esac
done


